### PR TITLE
fix some corner cases in github rate limiting

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by g-arjones** [comment]
Looks good.. Could you fix the test suite, please (it seems it was already broken before the patch)?

**Comment by doudou** [comment]
It's failing on 2.3.6 because of rubocop. I'm guessing that the rubocop version is blocked to an older one on 2.3 and that would be why.

I would simply remove 2.3 as a target on Travis (and add 2.7). What do you think ?

**Comment by g-arjones** [comment]
Sounds good to me... :+1:

**Comment by g-arjones** [comment]
@doudou This is in your backlog, right?

Just confirming you didn't lose track of it

**Comment by doudou** [comment]
Yes and no. The CI doesn't pass because of rubocop, and we have to move out of Travis because they have become very open-source-unfriendly. I don't remember why, but removing 2.3 and changing the rubocop version wasn't enough to get the CI to pass. 

I started moving to GH actions, but then hit a wall as well because the default linter action has rubocop 1.6. Started looking into that.

So, it's in my backlog, but I don't have the time required to get the CI changes to completion.

**Comment by g-arjones** [comment]
If you are willing to, feel free to either:

1. Merge as is;
2. Disable the linter;

Since we are essentially the only ones maintaining this I think having the linter off in the CI is not that bad. It would be really unfortunate to have a failing build as well but even that is probably better than keeping this unmerged for the foreseeable future.

**Comment by g-arjones** [comment]
I'm approving, the changes look good and I am ok with whatever you decide to do. Thanks for taking the time.

**Review by g-arjones — APPROVED** [review]

**Comment by doudou** [comment]
> Since we are essentially the only ones maintaining this I think having the linter off in the CI is not that bad

Given that we put the effort to have the linter while we were the only ones maintaining this, **because** we felt it was really needed, I thought it was a slippery slope.

Managed to get everything to work & pass.

**Pull request merged**
