### PR TITLE
fix build loop between open and push

### PR DESCRIPTION
**Pull request by doudou**
This solves a build loop where a push event would be processed, and
then the pull request open event. Since both have different SHA, and
both would update the cache, they ended up building in a loop

~~~
push: cache==SHA_OPEN != SHA_PUSH => build, cache:=SHA_PUSH
open: cache==SHA_PUSH != SHA_OPEN => build, cache:=SHA_OPEN
~~~

### CODE REVIEW

**Comment by g-arjones** [comment]
Sounds weird... If I remember correctly, the daemon only processes pushes on a branch that has a PR (among other things)

**Comment by doudou** [comment]
Well. It does filter the pushes on whether there is a branch for them. But that still fails:

First poll loop:
- push -> does nothing
- open -> creates branch, adds PR to cache. cache_sha == open_sha

Second poll loop:
- push -> cache_sha != push_sha, trigger build, cache_sha := push_sha
- open -> cache_sha != open_sha, trigger build, cache_sha := open_sha

**Comment by g-arjones** [comment]
I am not sure the problem really is what you describe. Push events that do not update the PR are ignored and, for a PR to be considered changed by the PullRequestCache, [on top of the head sha being different it also has to be more recent than the timestamp currently in the cache](https://github.com/rock-core/autoproj-daemon/blob/master/lib/autoproj/daemon/pull_request_cache.rb#L82).

Anyway, I don't see any problem with the change and since it broke the build loop you were experiencing, I'm fine with it.

**Review by g-arjones — APPROVED** [review]

**Comment by doudou** [comment]
I missed the timestamp part. Checked, and the timestamps of the two events that were causing the problem are indeed ordered properly. This PR is only fixing the symptom, not the problem.

Now, once rewritten, the code you just linked to is:

~~~
found.overrides != overrides ||
(
    (
         found.head_sha != pull_request.head_sha ||
         found.base_branch != pull_request.base_branch
    ) &&
   pull_request.updated_at > found.updated_at
)
~~~

So, if the overrides that are inferred are different, the `open` event will take precedence. I think we should just ignore older events. Do you agree ?

**Comment by g-arjones** [comment]
Not really, no. The overrides might be different because you changed the build configuration (without updating the PR) in which case you would want to trigger a build

**Comment by doudou** [comment]
> Not really, no. The overrides might be different because you changed the build configuration (without updating the PR) in which case you would want to trigger a build

Well, in that case we should be processing the *same* event (not an older event), so that would work with `pull_request.updated_at >= found.updated_at`. I think it's reasonable to use timestamp equality as a proxy for event equality (at least as a quick substitute to resolve the issue now)

**Comment by g-arjones** [comment]
Not sure I understand. Keep in mind that there are events that change the timestamp but we don't want to trigger builds for (comments, title changes, labels etc)

**Comment by doudou** [comment]
So. I've been re-thinking about it this morning, and started wondering why the overrides would be different in the two code paths. I really don't see how that could happen.

The bug is not triggering anymore. I'm guessing that's because [the dependency](https://github.com/orocos-toolchain/utilrb/pull/45) I added to [the pull request](https://github.com/orocos-toolchain/orogen/pull/138) got merged in the meantime.

I'm going to try and see whether I can artificially reproduce it (will create bogus pull requests and see what happens)

**Comment by g-arjones** [comment]
> wondering why the overrides would be different in the two code paths. I really don't see how that could happen

The only reason I see this happening is due to some kind of bug/instability in GitHub's API. The [overrides retriever will ignore items in the "depends on" list if the API reports one of the pull requests to be not found](https://github.com/rock-core/autoproj-daemon/blob/master/lib/autoproj/daemon/overrides_retriever.rb#L69). If that you were to happen "randomly", then you would have inconsistent overrides.

Other than that, the failure/bug could be in the buildconf branch creation/check part but you would notice "Creating branch..." messages in the logs rather than the more common "Triggering build..."

> The bug is not triggering anymore.

Been there :(

> I'm guessing that's because the dependency I added to the pull request got merged in the meantime.

I don't know how that would matter but that is a Draft pull request and I didn't do any testing with them when I was writing the daemon. Maybe there's something there. Just food for thought.

**Comment by g-arjones** [comment]
> that is a Draft pull request

I also wonder whether the daemon should ignore these

**Comment by doudou** [comment]
> I also wonder whether the daemon should ignore these

I actually use these when I want CI to test a PR, but let people know it's work in progress. So I'd rather not.

The issue is pretty simple: the 'body' field in the event is the body at the time **of** the event. So, the 'open' event has the old text, the 'push' event the new text and the overrides differ.

An alternative to my previous suggestion (that I will clarify later in this comment) would be to just use the events as hints that something changed on a PR, and process the pull request. It will pretty much unify the "PR open" and "PR push" codepaths and for that I think it's a good one.

My previous suggestion was to modify the `changed?` predicate to reject any event **strictly** older than the oldest. This would test for changes when processing the same event (== same timestamp) and therefore catch the case where overrides have changed, while avoid re-processing older events.

~~~
return false if found.updated_at > pull_request.updated_at

found.overrides != pull_request.overrides ||
   found.head_sha != pull_request.head_sha ||
   found.base_branch != pull_request.base_branch
~~~

**Comment by doudou** [comment]
In any case, I'm closing this one which is bogus

**Comment by g-arjones** [comment]
> The issue is pretty simple: the 'body' field in the event is the body at the time of the event. So, the 'open' event has the old text, the 'push' event the new text and the overrides differ.

I think you nailed it.

> ```ruby
> return false if found.updated_at > pull_request.updated_at
> found.overrides != pull_request.overrides ||
>   found.head_sha != pull_request.head_sha ||
>   found.base_branch != pull_request.base_branch
> ```

Hmm.. I think that's a good change as well (assuming you meant `found.updated_at >= pull_request.updated_at` instead)

**Pull request closed without merging**
