### PR TITLE
fix: better handle errors during the update process

### PR DESCRIPTION
**Pull request by doudou**
What triggered this work was the merge of a branch that was currently the mainline of a
package. This caused the daemon to quit (update_package_branches would raise), and
updating the mainline would not fix the problem since we called update_package_branches
first.

### CODE REVIEW

**Comment by g-arjones** [comment]
Ignoring the failure makes sense, I think the missing branch won't be a problem for the other requests (i.e `#update_pull_requests`). Now, whether `#handle_mainline_changes` or `#update_package_branches` gets called first doesn't make any difference, as far as I can remember. I mean, for your particular use case (you probably had an override in your buildconf) calling `#handle_mainline_changes` will probably save the daemon from some unnecessary work but if the mainline was changed in a package set then `handle_mainline_changes` before `#update_package_branches` is a no-op.

It also means you will always have a no-op `#handle_mainline_changes` when `#poll` is run for the first time (i.e after an update).

**Review by g-arjones — APPROVED** [review]

**Comment by g-arjones** [comment]
Semantically, it makes more sense to update branches first and it is more efficient in normal conditions.

**Comment by doudou** [comment]
> Semantically, it makes more sense to update branches first

Got it, thanks. Maybe I should keep the current order but put handle_mainline_changes in an ensure block ? And change `handle_mainline_changes` to check for buildconf change in all cases as well ? What do you think ?

**Comment by g-arjones** [comment]
Ultimately, the goal was to have the daemon working in a kind of a "safe mode" in which case it would just wait for pushes to the mainline hoping that someone would fix the workspace externally. What I didn't consider was `update_package_branches` breaking permanently. The idea of a safety net in an `ensure` block is a good one but rather than calling `handle_mainline_changes` (which can also fail) I think I would just do `updater.restart_and_update` (with a sleep before the actual method call to avoid updating in quick succession). That, combined with systemd managing the daemon process, should allow it to recover from most reasonable fail modes.

**Comment by doudou** [comment]
Done

**Comment by g-arjones** [comment]
Looks good to me but rubocop is failing

**Pull request merged**
